
replicaCount: 1
image:
  repository: abhishekf5/go-web-app
  pullPolicy: IfNotPresent
  tag: "10182393954"

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: go-web-app.local
      paths:
        - path: /
          pathType: ImplementationSpecific